FROM base:v1
RUN yum update -y \
    &&  yum install -y gperftools gperftools-devel \
    && yum install -y epel-release \
    && yum install -y python-pip \
    && pip install requests -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com \
    && mkdir -p /opt/manager/logs \
    && mkdir -p /opt/manager/ds \
    && mkdir -p /opt/manager/files \
    && ln -sf /dev/stdout /opt/manager/logs/info.log  \
    && ln -sf /dev/stderr /opt/manager/logs/error.log \
    && curl -O https://arthas.aliyun.com/arthas-boot.jar
WORKDIR /opt/manager
VOLUME ["/opt/manager/ds","/opt/manager/logs","/opt/manager/files"]
COPY data-job.jar check_start.sh check_start.py ./
ENV  spring_profiles_active=docker \
     NACOS_ADDR=""\
     NACOS_USERNAME=""\
     NACOS_PASSSWORD=""\
     REDIS_DATABASE="" \
     REDIS_HOST="" \
     REDIS_PORT="" \
     REDIS_PASSWORD="" \
     MYSQL_HOST="" \
     MYSQL_PORT="" \
     MYSQL_DATABASE="" \
     MYSQL_USERNAME="" \
     MYSQL_PASSWORD="" \
     MAIL_HOST="" \
     MAIL_PORT="" \
     MAIL_USERNAME="" \
     MAIL_PASSWORD="" \
EXPOSE 8080
ENTRYPOINT sh check_start.sh
